In [ ]:
import pandas as pd
from python.plots import distplot
from python.plots import convergence_plot

In [1]:
import respy as rp
import pandas as pd
from python.quantity_of_interest import model_wrapper_kw_94

_, base_options = rp.get_example_model("kw_94_one", with_data=False)
rp_params_chol = pd.read_pickle("python/input/rp_params_chol.uq.pkl")
_, edu_shares_df, _ = model_wrapper_kw_94(rp_params_chol, base_options, 0, add_qoi_edu_choices=True)

In [2]:
edu_shares_df

Choice    edu
Age
16      0.453
17      0.293
18      0.244
19      0.227
20      0.197
21      0.171
22      0.165
23      0.153
24      0.133
25      0.107
26      0.076
27      0.070
28      0.064
29      0.047
30      0.045
31      0.039
32      0.039
33      0.026
34      0.017
35      0.012
36      0.005
37      0.009
38      0.006
39      0.003
40      0.000
41      0.001
42      0.001
43      0.000
44      0.000
45      0.000
46      0.000
47      0.000
48      0.000
49      0.000
50      0.000
51      0.000
52      0.000
53      0.000
54      0.000
55      0.000

In [ ]:
qoi_base = pd.read_pickle("python/results/base_quantity.uq.pkl")

qoi_mc = pd.read_pickle("python/results/mc_quantity.uq.pkl")
params_mc = pd.read_pickle("python/results/mc_params.uq.pkl")

In [ ]:
distplot(qoi_mc["avg_schooling"], "qoi", save=True)

In [ ]:
import numpy as np
np.mean(qoi_mc)

In [ ]:
convergence_plot(qoi_mc["avg_schooling"], qoi_base["avg_schooling"][0], "QoI", absolute_deviation=False, save=True)

In [ ]:
convergence_plot(qoi_mc["avg_schooling"], qoi_base["avg_schooling"][0], "QoI", absolute_deviation=True, save=True)